language: python
sudo: false
python:
  - "3.6"
  - "3.7"
  - "3.8"
env:
  - DJANGO=2.2.8
  - DJANGO=3.0.3
  - DJANGO=3.1.1
install:
  - pip install --upgrade pip
  - pip install -q Django==$DJANGO
  - pip install coveralls
script:
  - coverage run --source=. runtests.py
after_success:
  - coveralls
notifications:
  email:
    on_failure: never
    on_success: never
